name: gladosCheckIn
on:
  workflow_dispatch:
  schedule:
    - cron:  '20 16 * * *'
jobs:
    checkIn:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: '3.10'
        - name: Install dependencies
          run : pip install -r requirements.txt
        - name: Run script
          run : python3 main.py
          env: 
            BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
            COOKIE: ${{ secrets.COOKIE }}
            CHAT_ID: ${{ secrets.CHAT_ID }}
          